[package]
name = "gasoline-app"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
clap = { version = "*", features = ["unstable", "suggestions", "color"] }
clippy = "*"
iron = "*"
persistent = "*"
router = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
stopwatch = "*"