[package]
name = "gasoline-core"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
chrono = "*"
clap = {version = "*", features = ["unstable", "suggestions", "color"]}
clippy = {version = "*", optional = true}
gasoline-data = {git = "https://github.com/archer884/gasoline-data.git"}
iron = "*"
mount = "*"
persistent = "*"
router = "*"
rwt = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
stopwatch = "*"

[features]
default = []
